# grab data with pandas and fix unicode index

In [17]:
import pandas as pd
import os 

path  = '../data/'
dirli = os.listdir(path)
pd.DataFrame(dirli)

# INDEX
i = 0
sheet = dirli[i]
df = pd.read_csv(path+sheet)
df

# CONDITIONAL INDEX

if 'time' in df.columns.str.lower():
    print('its a unicode index ')
    df = df.set_index('time')
    df.index = pd.to_datetime(df.index,unit='s')
    df.index = df.index - pd.Timedelta(hours=4)
elif 'datetime' in df.columns.str.lower():
    df = df.set_index('datetime')
elif 'date' in df.columns.str.lower():
    df = df.set_index('date')
    
df.head()
destpath = 'data/'
if not os.path.exists(destpath):
    os.mkdir(destpath)

df.to_csv(destpath+sheet)

its a unicode index

In [18]:
df

,open,high,low,close,Plot,Plot.1,Plot.2,Plot.3,Plot.4,Volume,...,a boaring middle line,a_boaring_line,a_boaring_line.1,buy,sell_sig,sell_sig.1,sell_sig.2,sell_sig.3,test,RSI
time,,,,,,,,,,,,,,,,,,,,,
2008-11-11 19:30:00,9.30,9.30,9.30,9.30,NaN,NaN,NaN,NaN,NaN,701,...,50.0,90.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2008-11-28 14:30:00,10.85,10.85,10.85,10.85,NaN,NaN,NaN,NaN,NaN,500,...,50.0,90.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2008-12-01 20:30:00,11.97,11.97,11.97,11.97,NaN,NaN,NaN,NaN,NaN,200,...,50.0,90.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,100.000000
2008-12-03 14:30:00,11.95,11.95,11.95,11.95,NaN,11.0175,NaN,NaN,NaN,500,...,50.0,90.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,98.523985
2008-12-03 15:30:00,12.41,12.41,12.41,12.41,11.296000,11.7950,NaN,NaN,NaN,100,...,50.0,90.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,99.120879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-30 15:30:00,22.51,22.80,22.51,22.80,21.709060,22.7325,19.919500,NaN,NaN,200,...,50.0,90.0,10.0,0.0,1.0,0.0,1.0,0.0,0.0,72.140981
2020-10-30 17:30:00,23.24,23.24,23.24,23.24,22.015248,22.8875,20.056833,NaN,NaN,200,...,50.0,90.0,10.0,0.0,1.0,0.0,1.0,0.0,0.0,87.641958
2020-10-30 18:30:00,23.28,23.28,23.28,23.28,22.268199,22.9700,20.195833,NaN,NaN,100,...,50.0,90.0,10.0,0.0,1.0,0.0,1.0,0.0,0.0,88.777303
2020-10-30 19:30:00,23.31,23.31,23.31,23.31,22.476559,23.1575,20.353500,NaN,NaN,200,...,50.0,90.0,10.0,0.0,1.0,0.0,1.0,0.0,0.0,90.136550
2020-11-03 14:30:00,23.68,23.68,23.61,23.61,22.703247,NaN,NaN,NaN,NaN,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.117903

##### the purpose of this is to continue to add uniformity to this work flow
#### so downloads and imports are the same across the board

# Data Grab - folder_style

In [3]:
'''
import shutil

#this grabs data from a specifyed directory: here we grab from one folder back called fdata
dpath = '../data'
dest  = 'data/'
shutil.copytree(dpath,dest)

#this case does not require it but there will also be preprocessing being done on theis script
'''

BATS VXX, 15.csv

In [5]:
#!gedit data_grab.py